// src/lib/toFramerCode.ts

export type FramerControlType = 'string' | 'number' | 'boolean' | 'color' | 'enum';

export interface FramerProp {
  name: string;
  type: FramerControlType;
  title: string;
  default: string | number | boolean;
  options?: string[];
  min?: number;
  max?: number;
  step?: number;
}

export function toFramerCode(
  rawCode: string,
  componentName: string,
  framerProps: FramerProp[]
): string {
  let code = rawCode;

  code = code.replace(
    /import gsap from ['"]gsap['"]/g,
    `// @ts-ignore — Framer uses CDN imports\nimport gsap from 'https://cdn.skypack.dev/gsap'`
  );
  code = code.replace(
    /import \{ ScrollTrigger \} from ['"]gsap\/ScrollTrigger['"]/g,
    `// @ts-ignore\nimport { ScrollTrigger } from 'https://cdn.skypack.dev/gsap/ScrollTrigger'`
  );
  code = code.replace(
    /import \{ SplitText \} from ['"]gsap\/SplitText['"]/g,
    `// @ts-ignore\nimport { SplitText } from 'https://cdn.skypack.dev/gsap/SplitText'`
  );

  const framerImport = `import { addPropertyControls, ControlType } from 'framer'`;
  const lastImportMatch = [...code.matchAll(/^import .+$/gm)].pop();
  if (lastImportMatch?.index !== undefined) {
    const insertAt = lastImportMatch.index + lastImportMatch[0].length;
    code = code.slice(0, insertAt) + '\n' + framerImport + code.slice(insertAt);
  } else {
    code = framerImport + '\n\n' + code;
  }

  if (framerProps.length > 0) {
    code = code.trimEnd() + '\n\n' + buildPropertyControls(componentName, framerProps);
  }

  const header = [
    `// Framer Code Component — generated by Kinetic UI`,
    `// HOW TO USE:`,
    `// 1. Open Framer → Assets → Code → "+ New File"`,
    `// 2. Paste this entire file and save`,
    `// 3. Drag the component from Assets onto your canvas`,
    `// 4. Edit props in the right panel — no code needed`,
    ``,
  ].join('\n');

  return header + code;
}

function buildPropertyControls(componentName: string, props: FramerProp[]): string {
  const controls = props.map((p) => {
    const lines: string[] = [`    ${p.name}: {`];
    lines.push(`      type: ControlType.${capitalize(p.type)},`);
    lines.push(`      title: '${p.title}',`);
    if (p.type === 'string' || p.type === 'color') {
      lines.push(`      defaultValue: '${p.default}',`);
    } else if (p.type === 'number') {
      lines.push(`      defaultValue: ${p.default},`);
      if (p.min !== undefined) lines.push(`      min: ${p.min},`);
      if (p.max !== undefined) lines.push(`      max: ${p.max},`);
      if (p.step !== undefined) lines.push(`      step: ${p.step},`);
    } else if (p.type === 'boolean') {
      lines.push(`      defaultValue: ${p.default},`);
    } else if (p.type === 'enum' && p.options) {
      lines.push(`      options: [${p.options.map((o) => `'${o}'`).join(', ')}],`);
      lines.push(`      defaultValue: '${p.default}',`);
    }
    lines.push(`    },`);
    return lines.join('\n');
  });
  return [`addPropertyControls(${componentName}, {`, controls.join('\n'), `});`].join('\n');
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
