// src/lib/toFramerCode.ts

export type FramerControlType = 'string' | 'number' | 'boolean' | 'color' | 'enum';

export interface FramerProp {
  name: string;
  type: FramerControlType;
  title: string;
  default: string | number | boolean;
  options?: string[];
  min?: number;
  max?: number;
  step?: number;
}

// Known internal hooks — import is removed and replaced with an inline implementation
const INTERNAL_HOOK_INLINES: Array<{ pattern: RegExp; inline: string }> = [
  {
    pattern: /import \{[^}]+\} from ['"]@\/hooks\/use-mobile['"]\n?/g,
    inline: `// Inlined: @/hooks/use-mobile
function useIsMobile(): boolean {
  const [v, setV] = React.useState<boolean>(typeof window !== 'undefined' ? window.innerWidth < 768 : false);
  React.useEffect(() => {
    const mql = window.matchMedia('(max-width: 767px)');
    const h = (e: MediaQueryListEvent): void => setV(e.matches);
    mql.addEventListener('change', h);
    return () => mql.removeEventListener('change', h);
  }, []);
  return v;
}
function useIsTouch(): boolean {
  return typeof window !== 'undefined' && ('ontouchstart' in window || navigator.maxTouchPoints > 0);
}
`,
  },
  {
    pattern: /import \{[^}]+\} from ['"]@\/hooks\/usePro['"]\n?/g,
    inline: `// Inlined: @/hooks/usePro (Pro gate disabled in Framer)\nfunction usePro(): boolean { return true; }\n`,
  },
];

// Any remaining @/ import that wasn't inlined above gets stripped with a comment
const STRIP_INTERNAL_IMPORTS = /import \{[^}]+\} from ['"]@\/[^'"]+['"]\n?/g;

export function toFramerCode(
  rawCode: string,
  componentName: string,
  framerProps: FramerProp[]
): string {
  let code = rawCode;

  // 1. Swap GSAP npm imports → CDN
  code = code.replace(
    /import gsap from ['"]gsap['"]/g,
    `// @ts-ignore — Framer uses CDN imports\nimport gsap from 'https://cdn.skypack.dev/gsap'`
  );
  code = code.replace(
    /import \{ ScrollTrigger \} from ['"]gsap\/ScrollTrigger['"]/g,
    `// @ts-ignore\nimport { ScrollTrigger } from 'https://cdn.skypack.dev/gsap/ScrollTrigger'`
  );
  code = code.replace(
    /import \{ SplitText \} from ['"]gsap\/SplitText['"]/g,
    `// @ts-ignore\nimport { SplitText } from 'https://cdn.skypack.dev/gsap/SplitText'`
  );

  // 2. Replace known internal hook imports with inlined implementations
  for (const { pattern, inline } of INTERNAL_HOOK_INLINES) {
    if (pattern.test(code)) {
      code = code.replace(pattern, '');
      code = injectAfterLastImport(code, inline);
    }
    pattern.lastIndex = 0;
  }

  // 3. Strip any remaining @/ imports — they don't resolve in Framer
  code = code.replace(STRIP_INTERNAL_IMPORTS, (match) => {
    const what = match.match(/import \{([^}]+)\}/)?.[1]?.trim() ?? 'unknown';
    return `// [Framer] Removed unresolvable import: { ${what} }\n`;
  });

  // 4. Inject Framer import after last import
  code = injectAfterLastImport(code, `import { addPropertyControls, ControlType } from 'framer'`);

  // 5. Append addPropertyControls
  if (framerProps.length > 0) {
    code = code.trimEnd() + '\n\n' + buildPropertyControls(componentName, framerProps);
  }

  // 6. Prepend usage header
  const header = [
    `// Framer Code Component — generated by Kinetic UI`,
    `// HOW TO USE:`,
    `// 1. Open Framer → Assets → Code → "+ New File"`,
    `// 2. Paste this entire file and save`,
    `// 3. Drag the component from Assets onto your canvas`,
    `// 4. Edit props in the right panel — no code needed`,
    ``,
  ].join('\n');

  return header + code;
}

function injectAfterLastImport(code: string, toInject: string): string {
  const matches = [...code.matchAll(/^import .+$/gm)];
  const last = matches.pop();
  if (last?.index !== undefined) {
    const insertAt = last.index + last[0].length;
    return code.slice(0, insertAt) + '\n' + toInject + code.slice(insertAt);
  }
  return toInject + '\n\n' + code;
}

function buildPropertyControls(componentName: string, props: FramerProp[]): string {
  const controls = props.map((p) => {
    const lines: string[] = [`    ${p.name}: {`];
    lines.push(`      type: ControlType.${capitalize(p.type)},`);
    lines.push(`      title: '${p.title}',`);
    if (p.type === 'string' || p.type === 'color') {
      lines.push(`      defaultValue: '${p.default}',`);
    } else if (p.type === 'number') {
      lines.push(`      defaultValue: ${p.default},`);
      if (p.min !== undefined) lines.push(`      min: ${p.min},`);
      if (p.max !== undefined) lines.push(`      max: ${p.max},`);
      if (p.step !== undefined) lines.push(`      step: ${p.step},`);
    } else if (p.type === 'boolean') {
      lines.push(`      defaultValue: ${p.default},`);
    } else if (p.type === 'enum' && p.options) {
      lines.push(`      options: [${p.options.map((o) => `'${o}'`).join(', ')}],`);
      lines.push(`      defaultValue: '${p.default}',`);
    }
    lines.push(`    },`);
    return lines.join('\n');
  });
  return [`addPropertyControls(${componentName}, {`, controls.join('\n'), `});`].join('\n');
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
